Add a check that we're not importing solution into build environment (#49)

diff --git a/.github/workflows/import-dqt20-solution.yml b/.github/workflows/import-dqt20-solution.yml
--- a/.github/workflows/import-dqt20-solution.yml
+++ b/.github/workflows/import-dqt20-solution.yml
@@ -14,6 +14,14 @@ jobs:
     concurrency: import-dqt20-${{ github.event.inputs.environment }}
 
     steps:
+    - run: |
+        if [ "$ENVIRONMENT" == "build" ]; then
+          echo "::error ::Cannot deploy to the build environment"
+          exit 1
+        fi
+      env:
+        ENVIRONMENT: ${{ github.event.inputs.environment }}
+
     - uses: actions/checkout@v2
 
     - uses: Azure/login@v1
